### ISSUE TITLE
Allow launching TensorBoard after training has finished

### ISSUE THREAD

**Issue by ChengbingLiu** [tony-framework/TonY#356]
When the training job is running, TensorBoard can be easily accessed through the AM tracking link. It will be much more convenient if we allow user to launch TensorBoard even after the training has finished. Do we have an idea or plan for this?

**Comment by erwa** [comment]
What we do is we have a pre-built Python PEX virtual environment with TensorBoard already installed with an entry point that launches TensorBoard. And then we have a simple launcher script we put on our gateway machines that users run to launch TensorBoard. Something like `start-tensorboard.py /path/to/log/dir`. The script just uses `ClusterSubmitter` to launch TB.
