### ISSUE TITLE
Please open a security advisory

### ISSUE THREAD

**Issue by JLLeitschuh** [tony-framework/TonY#496]
Hello,

I'm an independent security researcher performing security research under the [GitHub Security Lab Bug Bounty Program](https://securitylab.github.com/). I believe I may have found a security vulnerability in this project.

Please open a security advisory against this repository so we can privately discuss the details. This advisory can be opened by a user with admin permissions on this repository.

https://github.com/linkedin/TonY/security/advisories

**Comment by oliverhu** [comment]
@JLLeitschuh sorry for the late reply, added you to the discussion!
