### ISSUE TITLE
Introduce generic tony listener interface

### ISSUE THREAD

**Issue by zuston** [tony-framework/TonY#589]
### Why 
We need to collect application time of waiting resources and some metrics. So it's better to introduce generic tony listener interface like `SparkListenerInterface`, and for user it's easy to implement custom listener to callback.

### Example
```java
public interface TonyListenerInterface {
    void onApplicationStart(ApplicationContext context);
    void onApplicationEnd(ApplicationContext context);
    void onTaskExecutorAllocated(ApplicationContext context);
    void onTaskExecutorRegistered(ApplicationContext context);
    void onTaskExecutorEnd(ApplicationContext context);
}
```

**Comment by zuston** [comment]
@oliverhu Please check it

**Comment by oliverhu** [comment]
Do we need a generic interface? the waiting resources & metrics collection seem needed for all?
