### ISSUE TITLE
Can the training task run with  docker container, and the hadoop cluster run without  docker container?

### ISSUE THREAD

**Issue by jxfruit** [tony-framework/TonY#601]
May I have a question about docker mode?
Can the training task run with  docker container, and the hadoop cluster run without  docker container?

**Comment by zuston** [comment]
@jxfruit  Of course. If want to training on docker, the higher hadoop version should be needed, like hadoop3.x.

Can you describe more details?

**Comment by jxfruit** [comment]
OK，training codes and tony client will be packaged running on docker, which cannot depend on the docker containerized hadoop cluster, right? 
Can u provide some docs?
And are there some examples about my issue?
tks a lot

**Comment by zuston** [comment]
Doc is [here](https://github.com/tony-framework/TonY#use-a-docker-container). Any question can be issued here.

**Comment by zuston** [comment]
@jxfruit 
TonY now support two options to run tensorflow/pytorch jobs.
1. python venv
2. using the docker which is depended on Hadoop3.x supporting docker runtime

Could you describe more details on your cluster information like Hadoop version?
If you want to know more about the TonY examples or best practices, please send to my email: junfan.zhang@outlook.com.
Maybe we could chat offline

**Comment by jxfruit** [comment]
@zuston Thanks a lot. And I have sent an email.
