### ISSUE TITLE
Should job fail fast when missing heartbeats ?

### ISSUE THREAD

**Issue by zuston** [tony-framework/TonY#606]
Now when task missed heartbeats, the job will fail fast using [method `onTaskDeemedDead`](https://github.com/tony-framework/TonY/blob/f78e171064237421da27ae00cd620e7f57d409dd/tony-core/src/main/java/com/linkedin/tony/ApplicationMaster.java#L1229). But i think it should keep consistent with container-completed-action, like [method: `processFinishedContainer`](https://github.com/tony-framework/TonY/blob/f78e171064237421da27ae00cd620e7f57d409dd/tony-core/src/main/java/com/linkedin/tony/ApplicationMaster.java#L1238)

**Comment by oliverhu** [comment]
Agreed..there are some areas of improvements to make the handling more consistent

**Comment by zuston** [comment]
Close it. Fix #607
