### ISSUE TITLE
Configurable status when dependency times out

### ISSUE THREAD

**Issue by oliverhu** [tony-framework/TonY#641]
Follow up from #621 . 
In some of the cases, we don't want to fail the whole job even though a dependency times out. For example, if `chief` succeeded and there is a `worker` hanging for 1 hour, users can configure the job to still pass.

```
tony.application.group.A = worker,chief
tony.application.dependency.evaluator.timeout.after.A = 3600
tony.application.dependency.evaluator.timeout.after.A.ignored = true
```
@zuston thoughts?

**Comment by zuston** [comment]
Make sense

**Comment by zuston** [comment]
Updated version on https://github.com/tony-framework/TonY/pull/643 @oliverhu
