### ISSUE TITLE
Failed to get RM principal

### ISSUE THREAD

**Issue by Alpaca4610** [tony-framework/TonY#670]
Hi, I have the following problem when I run the pytorch program using TonY. How can I solve this problem please? Thank you for your help!

`2022-05-25 00:11:50,366 INFO tony.TonyClient: Running with secure cluster mode. Fetching delegation tokens..
2022-05-25 00:11:50,367 INFO tony.TonyClient: Fetching RM delegation token..
Exception in thread "main" java.lang.RuntimeException: Failed to get RM principal.`

**Comment by oliverhu** [comment]
Most likely it is because you're not running in a secure cluster (not kerberized). You can set `tony.application.security.enabled` to `false`

**Comment by Alpaca4610** [comment]
Thank you for your help!
