### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hadoop/fs/FSDataOutputStream

### ISSUE THREAD

**Issue by Alpaca4610** [tony-framework/TonY#672]
Hi, I have a new problem running the pytorch program with TonY. The problem seems to be related to hadoop classpath. The error is reported as follows. 
`Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hadoop/fs/FSDataOutputStream`
I executed the following command, but it still doesn't work.
`export HADOOP_CLASSPATH=$(find $HADOOP_HOME -name '*.jar' | xargs echo | tr ' ' ':')`
 My Hadoop was installed following the steps given in the TonY documentation.

**Comment by oliverhu** [comment]
you can set the ENV with the `tony.containers.envs` config
